name: Just a workflow

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  do-stuff:
    name: what's in a name?
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - name: do the thing
        id: do-thing
        run: |-
          echo "Yolo all the way"
