name: Just a workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - name: do the thing
        id: do-thing
        run: |
          echo "Yolo all the way"